import { formatDateForICS, formatDateOnlyForICS } from './dateUtils.ts';
import { BatchConfig } from '../types.ts';

export const generateICSContent = (
  selectedDates: Date[],
  config: BatchConfig
): string => {
  const { reason, startTime, endTime, alert, alert2, isAllDay } = config;

  let icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AppleCalendarBatchEvent//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Batch Events
`;

  selectedDates.forEach((date) => {
    const now = new Date();
    
    let dtStartLine = '';
    let dtEndLine = '';

    if (isAllDay) {
        // All Day Event: DTSTART;VALUE=DATE:YYYYMMDD
        // DTEND is typically the next day for a 1-day event
        const eventStart = new Date(date);
        const eventEnd = new Date(date);
        eventEnd.setDate(eventEnd.getDate() + 1);

        dtStartLine = `DTSTART;VALUE=DATE:${formatDateOnlyForICS(eventStart)}`;
        dtEndLine = `DTEND;VALUE=DATE:${formatDateOnlyForICS(eventEnd)}`;
    } else {
        // Time Based Event
        const [startH, startM] = startTime.split(':').map(Number);
        const [endH, endM] = endTime.split(':').map(Number);

        const eventStart = new Date(date);
        eventStart.setHours(startH, startM, 0);

        const eventEnd = new Date(date);
        eventEnd.setHours(endH, endM, 0);

        // If end time is before start time, assume it ends the next day
        if (eventEnd < eventStart) {
            eventEnd.setDate(eventEnd.getDate() + 1);
        }

        dtStartLine = `DTSTART:${formatDateForICS(eventStart)}`;
        dtEndLine = `DTEND:${formatDateForICS(eventEnd)}`;
    }

    icsContent += `BEGIN:VEVENT
DTSTAMP:${formatDateForICS(now)}Z
${dtStartLine}
${dtEndLine}
SUMMARY:${reason || 'Busy'}
DESCRIPTION:Generated by Apple Calendar Batch Event
STATUS:CONFIRMED
SEQUENCE:0
TRANSP:${isAllDay ? 'TRANSPARENT' : 'OPAQUE'}
`;

    // Alerts are typically less common on all-day events unless specified, 
    // but if the user requested them, we include them relative to start time.
    if (alert && alert !== 'none') {
      icsContent += `BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:${reason || 'Busy'}
TRIGGER:${alert}
END:VALARM
`;
    }

    if (alert2 && alert2 !== 'none') {
      icsContent += `BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:${reason || 'Busy'}
TRIGGER:${alert2}
END:VALARM
`;
    }

    icsContent += `END:VEVENT
`;
  });

  icsContent += `END:VCALENDAR`;
  return icsContent;
};

export const downloadICS = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${filename}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};